# Generated by Django 4.2 on 2026-05-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer_alter_pokemon_height_alter_pokemon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('F', 'Fuego'), ('T', 'Tierra'), ('L', 'Lagartija'), ('P', 'Planta'), ('E', 'Eléctrico')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
